name: Release

on:
  workflow_run:
    workflows: ["Parallel Component Validation"]
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  # ==========================================
  # RELEASE GATE VERIFICATION
  # ==========================================
  
  verify-build-success:
    name: 🔍 Verify Build Success
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      release-approved: ${{ steps.verify.outputs.approved }}
    steps:
      - name: Verify parallel build passed
        id: verify
        run: |
          echo "Verifying that parallel component validation succeeded..."
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "✅ Parallel component validation passed"
            echo "approved=true" >> $GITHUB_OUTPUT
          else
            echo "❌ Parallel component validation failed"
            echo "approved=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Log release approval
        run: |
          echo "🎉 All platform components validated successfully!"
          echo "✅ Frontend (SvelteKit) - Build, lint, test, type-check passed"
          echo "✅ GraphQL Server (Node.js) - Build, lint, test, type-check passed"  
          echo "✅ Mobile App (Flutter) - Build, analyze, test passed"
          echo "✅ Database (MongoDB + Neo4j) - Schema validation passed"
          echo "✅ Integration tests - API connectivity verified"
          echo "✅ Docker builds - All images build successfully"
          echo ""
          echo "🚀 PROCEEDING WITH RELEASE"

  # ==========================================
  # SEMANTIC RELEASE
  # ==========================================
  
  release:
    name: 🚀 Semantic Release
    runs-on: ubuntu-latest
    needs: verify-build-success
    if: needs.verify-build-success.outputs.release-approved == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use the commit that triggered the original workflow
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Verify dependency integrity
        run: npm audit signatures

      - name: Download build artifacts from parallel validation
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify build artifacts exist
        run: |
          echo "Verifying build artifacts from parallel validation..."
          if [ -d "frontend-build" ]; then
            echo "✅ Frontend build artifacts found"
          else
            echo "❌ Frontend build artifacts missing"
            exit 1
          fi
          
          if [ -d "server-build" ]; then
            echo "✅ Server build artifacts found"
          else
            echo "❌ Server build artifacts missing"
            exit 1
          fi
          
          if [ -f "mobile-app-debug-apk" ]; then
            echo "✅ Mobile app build artifacts found"
          else
            echo "⚠️ Mobile app artifacts not found (may be expected)"
          fi

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🚀 Starting semantic release process..."
          echo "All platform components have been validated and built successfully"
          npm run semantic-release

      - name: Release summary
        if: success()
        run: |
          echo "✅ RELEASE COMPLETED SUCCESSFULLY!"
          echo ""
          echo "📋 Release Summary:"
          echo "• All 4 platform components validated ✅"
          echo "• Integration tests passed ✅"  
          echo "• Docker images built ✅"
          echo "• Security scans completed ✅"
          echo "• Semantic release published ✅"
          echo ""
          echo "🎉 otw.sport platform release is live!"

  # ==========================================
  # RELEASE FAILURE HANDLING
  # ==========================================
  
  release-failed:
    name: 🚫 Release Failed
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'success'
    steps:
      - name: Log failure reason
        run: |
          echo "❌ RELEASE BLOCKED"
          echo ""
          echo "The parallel component validation workflow failed."
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo ""
          echo "🔧 Required actions:"
          echo "1. Check the parallel build workflow for specific failures"
          echo "2. Fix any failing components:"
          echo "   • Frontend (SvelteKit)"
          echo "   • GraphQL Server (Node.js)" 
          echo "   • Mobile App (Flutter)"
          echo "   • Database (MongoDB + Neo4j)"
          echo "   • Integration tests"
          echo "   • Docker builds"
          echo "3. Push fixes to trigger new validation"
          echo "4. Only when ALL components pass will release proceed"
          echo ""
          echo "🚫 No release will be created until all validations pass"
          
      - name: Create issue for failed release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚫 Release blocked - Component validation failed`,
              body: `## Release Blocked ❌
              
              The release process was blocked because the parallel component validation failed.
              
              **Failure Details:**
              - Workflow: ${{ github.event.workflow_run.name }}
              - Conclusion: ${{ github.event.workflow_run.conclusion }}
              - Run ID: ${{ github.event.workflow_run.id }}
              - Commit: ${{ github.event.workflow_run.head_sha }}
              
              **Action Required:**
              1. Review the [failed workflow run](${{ github.event.workflow_run.html_url }})
              2. Fix all component validation failures
              3. Push fixes to main branch
              4. Verify all components pass validation
              
              **Components that must pass:**
              - [ ] Frontend (SvelteKit) - build, lint, test, type-check
              - [ ] GraphQL Server (Node.js) - build, lint, test, type-check  
              - [ ] Mobile App (Flutter) - build, analyze, test
              - [ ] Database (MongoDB + Neo4j) - schema validation
              - [ ] Integration tests - API connectivity
              - [ ] Docker builds - image creation
              
              Release will automatically proceed once all validations pass. ✅`,
              labels: ['release', 'blocked', 'bug']
            })